version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly

    reviewers:
      - "01max"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - "01max"
