AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
